//
//  UIControl+Style.h
//  H2H
//
//  Created by Sagar Kasture on 01/03/16.
//  Copyright © 2016 Sagar Kasture. All rights reserved.
//

#import <UIKit/UIKit.h>

#pragma mark - UINavigationBar
@interface UINavigationBar (Style)
typedef NS_ENUM(NSUInteger, UINAVIGATIONBAR_STYLE)
{
    UINAVIGATIONBAR_STYLE_ASR,
    UINAVIGATIONBAR_STYLE_ASR_FOR_IPHONE
};
-(void) setStyle:(UINAVIGATIONBAR_STYLE)style;
@end

#pragma mark - UIView
@interface UIView (Style)
typedef NS_ENUM(NSUInteger, UIVIEW_STYLE)
{
    UIVIEW_STYLE_JOIN_MEETING,
    UIVIEW_STYLE_JOIN_MEETING_CONTENT,
    UIVIEW_STYLE_USER_MESSAGE_BACKGROUND,
    UIVIEW_STYLE_PARTICIPANT_MESSAGE_BACKGROUND,
    UIVIEW_STYLE_PARTICIPANT_MESSAGE_BACKGROUND_PLAIN,
    UIVIEW_STYLE_PARTICIPANT_MESSAGE_BACKGROUND_TRANSPARANT_IN,
    UIVIEW_STYLE_PARTICIPANT_MESSAGE_BACKGROUND_TRANSPARANT_OUT,
    UIVIEW_STYLE_USER_MESSAGE_BACKGROUND_PLAIN,
    UIVIEW_STYLE_USER_MESSAGE_BACKGROUND_FOR_TRANSPARENT,
    UIVIEW_STYLE_USER_MESSAGE_BACKGROUND_FOR_TRANSPARENT_IN,
    UIVIEW_STYLE_CHAT_VIEW_DISABLED_OVERLAY_BACKGROUND,
    
    UIVIEW_STYLE_CHAT_TRANSPARENT,
    UIVIEW_STYLE_CHAT_PLAIN,
    UIVIEW_STYLE_CHAT_OPAQUE,
    UIVIEW_STYLE_CHAT_USER,
    UIVIEW_STYLE_CHAT_PARTICIPANT
};
-(void) setStyle:(UIVIEW_STYLE)style;
@end

#pragma mark - UILabel
@interface UILabel (Style)
typedef NS_ENUM(NSUInteger, UILABEL_STYLE)
{
    UILABEL_STYLE_JOIN_MEETING_TITLE,
    UILABEL_STYLE_JOIN_MEETING_ERROR,
    UILABEL_STYLE_CHAT_TITLE,
    UILABEL_STYLE_USER_MESSAGE,
    UILABEL_STYLE_PARTICIPANT_MESSAGE,
    UILABEL_STYLE_JOIN_MEETING_FOOTER,
    UILABEL_STYLE_JOIN_MEETING_PLACEHOLDER,
    UILABEL_STYLE_PARTICIPANT_MANAGEMENT,
    UILABEL_STYLE_SWITCH_CHAT_LIST,
    UI_LABEL_STYLE_LIST_TITLE,
    UI_LABEL_STYLE_LIST_TITLE_SELECTED,
    UI_LABEL_STYLE_REMINDER_TIME,
    UI_LABEL_STYLE_HEADER_TITLE,
    UI_LABEL_STYLE_SUBTITLE_CENTER_ALIGN,
    UI_LABEL_STYLE_NETWORK_STATUS_CHECK,
    UI_LABEL_STYLE_NETWORK_STATUS_LIST,
    UILABEL_STYLE_CHAT_NAME,
    UI_LABEL_STYLE_CHAT_USER_LIST,
    UI_LABEL_STYLE_CHAT_PARTICIPANT_LIST,
    UILABEL_STYLE_HEADER_CHAT_NAME
};

-(void) setStyle:(UILABEL_STYLE)style;
@end

#pragma mark - UITextField
@interface UITextField (Style)
typedef NS_ENUM(NSUInteger, UITEXTFIELD_STYLE)
{
    UITEXTFIELD_STYLE_JOIN_MEETING
};
-(void) setStyle:(UITEXTFIELD_STYLE)style;
@end

#pragma mark - UITextView
@interface UITextView (Style)
typedef NS_ENUM(NSUInteger, UITEXTVIEW_STYLE)
{
    UITEXTVIEW_STYLE_USER_MESSAGE,
    UITEXTVIEW_STYLE_PARTICIPANT_MESSAGE,
};
-(void) setStyle:(UITEXTVIEW_STYLE)style;
@end

#pragma mark - UIButton
@interface UIButton (Style)
typedef NS_ENUM(NSUInteger, UIBUTTON_STYLE)
{
    UIBUTTON_STYLE_JOIN_MEETING,
    UIBUTTON_STYLE_VIDEO_VIEW_TOGGLE,
    UIBUTTON_STYLE_EDIT_CHAT_LIST,
    UIBUTTON_ATTRIBUTED_STYLE_SEND_TO_CHAT,
    UIBUTTON_STYLE_BORDER,
    UIBUTTON_STYLE_TOOLBAR,
    UIBUTTON_STYLE_SUBMIT_SUPPORT_REQUEST,
    UIBUTTON_STYLE_OVERLAY_WITH_BORDER
};
-(void) setStyle:(UIBUTTON_STYLE)style;
-(NSAttributedString*) setAttribuetedStyle:(UIBUTTON_STYLE)style forText:(NSString*) displayName;
@end

#pragma mark - UITableView
@interface UITableView (Style)
typedef NS_ENUM(NSUInteger, UITABLEVIEW_STYLE)
{
    UITABLEVIEW_STYLE_MESSAGES,
    UITABLEVIEW_STYLE_MESSAGES_FOR_TRANSPARENT_MODE,
    UITABLEVIEW_STYLE_MESSAGES_FOR_OPAQUE_MODE
    
};
-(void) setStyle:(UITABLEVIEW_STYLE)style;
@end

#pragma mark - UITableViewCell
@interface UITableViewCell (Style)
typedef NS_ENUM(NSUInteger, UITABLEVIEWCELL_STYLE)
{
    UITABLEVIEWCELL_STYLE_MESSAGES,
    UITABLEVIEWCELL_STYLE_DISABLED
};
-(void) setStyle:(UITABLEVIEWCELL_STYLE)style;
@end